package cn.feezu.maint.webservice.vehicle.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-03-30T15:00:02.670+08:00
 * Generated source version: 3.1.7
 */
public class CarService extends Service {

	public final static QName SERVICE = new QName("http://service.vehicle.meta.manage.wzc.com/", "carService");
	public final static QName CarServiceImplPort = new QName("http://service.vehicle.meta.manage.wzc.com/", "CarServiceImplPort");

	public CarService(String url) throws MalformedURLException {
		super(new URL(url + "/metadata/services/vehicle/carService?wsdl"), SERVICE);
	}

	@WebEndpoint(name = "CarServiceImplPort")
	public cn.feezu.maint.webservice.ws.vehicle.service.CarService getCarServiceImplPort() {
		return super.getPort(CarServiceImplPort, cn.feezu.maint.webservice.ws.vehicle.service.CarService.class);
	}

}
