package cn.feezu.maint.webservice.ws.vehicle.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-03-30T15:00:02.633+08:00
 * Generated source version: 3.1.7
 */
@WebService(targetNamespace = "http://service.vehicle.ws.meta.manage.wzc.com/", name = "CarService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CarService {

	@WebMethod
	@WebResult(name = "return", targetNamespace = "http://service.vehicle.ws.meta.manage.wzc.com/", partName = "return")
	public Result controlCarByManager(@WebParam(partName = "arg0", name = "arg0") String arg0, @WebParam(partName = "arg1", name = "arg1") String arg1);


	@WebMethod
	@WebResult(name = "return", targetNamespace = "http://service.vehicle.ws.meta.manage.wzc.com/", partName = "return")
	public CarDTOArray findCarInfoByLicense(@WebParam(partName = "arg0", name = "arg0") String arg0);
	
	/**
	 * 
	 * @param arg0
	 * @return returns cn.feezu.maint.webservice.ws.vehicle.service.CarObdDTO
	 */
	@WebMethod
	@WebResult(partName = "return")
	public CarObdDTO getCarObdInfoById(@WebParam(name = "arg0", partName = "arg0") String arg0);
}
