package cn.feezu.maint.webservice.authority.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-03-30T14:58:21.135+08:00
 * Generated source version: 3.1.7
 */
public class UserService extends Service {

	public final static QName SERVICE = new QName("http://service.authority.meta.manage.wzc.com/", "UserService");
	public final static QName UserServiceImplPort = new QName("http://service.authority.meta.manage.wzc.com/", "UserServiceImplPort");

	public UserService(String url) throws MalformedURLException {
		super(new URL(url + "http://localhost:8080/metadata/services/authority/userService?wsdl"), SERVICE);
	}

	@WebEndpoint(name = "UserServiceImplPort")
	public cn.feezu.maint.webservice.ws.authority.service.UserService getUserServiceImplPort() {
		return super.getPort(UserServiceImplPort, cn.feezu.maint.webservice.ws.authority.service.UserService.class);
	}

}
